import { HospiceFacility, FaqItem, GlossaryTerm } from './types';

// Real Data for Hospice Map (Representative samples for major cities)
export const MOCK_HOSPICE_DATA: HospiceFacility[] = [
  // --- West Coast ---
  {
    id: '1',
    name: "Providence Hospice of Seattle",
    type: "Non-profit",
    city: "Seattle",
    state: "WA",
    address: "2811 S 102nd St, Tukwila, WA 98168",
    phone: "(206) 320-4000",
    website: "https://www.providence.org/services/hospice",
    rating: 4.8,
    services: ["Home Hospice", "Palliative Care", "Grief Support", "Pediatric Hospice"],
    languages: ["English", "Spanish", "Vietnamese"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '2',
    name: "Hospice of Spokane",
    type: "Non-profit",
    city: "Spokane",
    state: "WA",
    address: "121 S Arthur St, Spokane, WA 99202",
    phone: "(509) 456-0438",
    website: "https://www.hospiceofspokane.org",
    rating: 4.7,
    services: ["Home Hospice", "Hospice House (Inpatient)", "Bereavement"],
    languages: ["English"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '3',
    name: "VITAS Healthcare Los Angeles",
    type: "For-profit",
    city: "Los Angeles",
    state: "CA",
    address: "1343 N Grand Ave, Walnut, CA 91789",
    phone: "(800) 938-4827",
    website: "https://www.vitas.com/locations-search/los-angeles-and-ventura",
    rating: 4.5,
    services: ["Home Hospice", "Inpatient Hospice Unit", "Telecare"],
    languages: ["English", "Spanish", "Tagalog", "Mandarin"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '4',
    name: "By the Bay Health",
    type: "Non-profit",
    city: "San Francisco",
    state: "CA",
    address: "17 E. Sir Francis Drake Blvd, Larkspur, CA 94939",
    phone: "(415) 927-2273",
    website: "https://bythebayhealth.org",
    rating: 4.9,
    services: ["Home Hospice", "Palliative Care", "Pediatric Care", "Camp for Kids"],
    languages: ["English", "Spanish", "Chinese"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '5',
    name: "The Elizabeth Hospice",
    type: "Non-profit",
    city: "San Diego",
    state: "CA",
    address: "500 La Terraza Blvd, Escondido, CA 92025",
    phone: "(800) 797-2050",
    website: "https://elizabethhospice.org",
    rating: 4.8,
    services: ["Home Hospice", "Palliative Care", "Veterans Program"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '6',
    name: "Hospice of the Valley",
    type: "Non-profit",
    city: "Phoenix",
    state: "AZ",
    address: "1510 E. Flower St, Phoenix, AZ 85014",
    phone: "(602) 530-6900",
    website: "https://www.hov.org",
    rating: 4.9,
    services: ["Home Hospice", "Inpatient Units", "Dementia Care", "Pulmonary Care"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '7',
    name: "Care Partners",
    type: "Non-profit",
    city: "Portland",
    state: "OR",
    address: "12630 SE Kelly St, Portland, OR 97236",
    phone: "(503) 619-8900",
    website: "https://carepartnersor.org",
    rating: 4.7,
    services: ["Home Hospice", "Palliative Care"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },

  // --- South & Southeast ---
  {
    id: '8',
    name: "Catholic Hospice",
    type: "Non-profit",
    city: "Miami",
    state: "FL",
    address: "14875 NW 77th Ave, Miami Lakes, FL 33014",
    phone: "(305) 822-2380",
    website: "https://www.catholichospice.org",
    rating: 4.6,
    services: ["Home Hospice", "Inpatient Care", "Jewish Hospice Program"],
    languages: ["English", "Spanish", "Haitian Creole"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '9',
    name: "LifePath Hospice",
    type: "Non-profit",
    city: "Tampa",
    state: "FL",
    address: "4200 W Cypress St, Tampa, FL 33607",
    phone: "(813) 877-2200",
    website: "https://www.chaptershealth.org/locations/lifepath-hospice",
    rating: 4.7,
    services: ["Home Hospice", "Grief Services", "Veterans Program"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '10',
    name: "Visiting Nurse Health System / Hospice Atlanta",
    type: "Non-profit",
    city: "Atlanta",
    state: "GA",
    address: "5775 Glenridge Dr, Atlanta, GA 30328",
    phone: "(404) 222-5000",
    website: "https://vnhs.org/services/hospice",
    rating: 4.5,
    services: ["Home Hospice", "Inpatient Center", "Camp STARS (Grief)"],
    languages: ["English"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '11',
    name: "Houston Hospice",
    type: "Non-profit",
    city: "Houston",
    state: "TX",
    address: "1905 Holcombe Blvd, Houston, TX 77030",
    phone: "(713) 467-7423",
    website: "https://www.houstonhospice.org",
    rating: 4.8,
    services: ["Home Hospice", "Inpatient Care", "Butterfly Program (Pediatric)"],
    languages: ["English", "Spanish", "Vietnamese"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '12',
    name: "Hospice Austin",
    type: "Non-profit",
    city: "Austin",
    state: "TX",
    address: "4107 Spicewood Springs Rd, Austin, TX 78759",
    phone: "(512) 342-4700",
    website: "https://www.hospiceaustin.org",
    rating: 4.9,
    services: ["Home Hospice", "Christopher House (Inpatient)", "Pet Peace of Mind"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '13',
    name: "Faith Presbyterian Hospice",
    type: "Non-profit",
    city: "Dallas",
    state: "TX",
    address: "12477 Merit Dr, Dallas, TX 75251",
    phone: "(972) 239-5300",
    website: "https://www.faithpreshospice.org",
    rating: 4.8,
    services: ["Home Hospice", "Inpatient Center", "Faith-Based Care"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '14',
    name: "Notre Dame Hospice",
    type: "Non-profit",
    city: "New Orleans",
    state: "LA",
    address: "1000 Howard Ave, New Orleans, LA 70113",
    phone: "(504) 596-4171",
    website: "https://notredamehealth.org/hospice",
    rating: 4.7,
    services: ["Home Hospice", "Pastoral Care"],
    languages: ["English", "French"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '15',
    name: "VIA Health Partners",
    type: "Non-profit",
    city: "Charlotte",
    state: "NC",
    address: "7845 Little Ave, Charlotte, NC 28226",
    phone: "(704) 375-0100",
    website: "https://www.viahp.org",
    rating: 4.8,
    services: ["Home Hospice", "Chameleon's Journey (Grief Camp)", "Kids Path"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '16',
    name: "Alive Hospice",
    type: "Non-profit",
    city: "Nashville",
    state: "TN",
    address: "1718 Patterson St, Nashville, TN 37203",
    phone: "(615) 327-1085",
    website: "https://www.alivehospice.org",
    rating: 4.7,
    services: ["Home Hospice", "Residence", "Grief Counseling"],
    languages: ["English"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },

  // --- Northeast ---
  {
    id: '17',
    name: "Care Dimensions",
    type: "Non-profit",
    city: "Boston",
    state: "MA",
    address: "75 Sylvan St, Danvers, MA 01923",
    phone: "(888) 283-1722",
    website: "https://www.caredimensions.org",
    rating: 4.8,
    services: ["Home Hospice", "Kaplan Family Hospice House", "Cardiac Support"],
    languages: ["English", "Spanish", "Portuguese"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '18',
    name: "Calvary Hospital Hospice",
    type: "Non-profit",
    city: "New York",
    state: "NY",
    address: "1740 Eastchester Rd, Bronx, NY 10461",
    phone: "(718) 518-2000",
    website: "https://www.calvaryhospital.org",
    rating: 4.9,
    services: ["Inpatient Hospital", "Home Hospice", "Palliative Care"],
    languages: ["English", "Spanish", "Russian", "Mandarin", "Yiddish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '19',
    name: "The Community Hospice",
    type: "Non-profit",
    city: "Albany",
    state: "NY",
    address: "445 New Karner Rd, Albany, NY 12205",
    phone: "(518) 724-0200",
    website: "https://www.communityhospice.org",
    rating: 4.6,
    services: ["Home Hospice", "Grief Center"],
    languages: ["English"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '20',
    name: "Penn Medicine Hospice",
    type: "Non-profit",
    city: "Philadelphia",
    state: "PA",
    address: "3535 Market St, Philadelphia, PA 19104",
    phone: "(800) 700-8807",
    website: "https://www.pennmedicine.org/for-patients-and-visitors/find-a-program-or-service/hospice",
    rating: 4.7,
    services: ["Home Hospice", "Inpatient Hospice", "Veterans Program"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '21',
    name: "Family Hospice (UPMC)",
    type: "Non-profit",
    city: "Pittsburgh",
    state: "PA",
    address: "700 Bower Hill Rd, Pittsburgh, PA 15243",
    phone: "(412) 572-8800",
    website: "https://www.upmc.com/services/home-health-care/hospice",
    rating: 4.5,
    services: ["Home Hospice", "Inpatient Unit", "Bereavement"],
    languages: ["English"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '22',
    name: "Barnabas Health Hospice",
    type: "Non-profit",
    city: "Newark",
    state: "NJ",
    address: "80 Main St, West Orange, NJ 07052",
    phone: "(973) 322-4800",
    website: "https://www.rwjbh.org/treatment-care/hospice",
    rating: 4.4,
    services: ["Home Hospice", "Palliative Care"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },

  // --- Midwest ---
  {
    id: '23',
    name: "Rainbow Hospice and Palliative Care",
    type: "Non-profit",
    city: "Chicago",
    state: "IL",
    address: "1550 Bishop Ct, Mount Prospect, IL 60056",
    phone: "(847) 685-9900",
    website: "https://rainbowhospice.org",
    rating: 4.8,
    services: ["Home Hospice", "Inpatient Unit", "Community Education"],
    languages: ["English", "Polish", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '24',
    name: "OhioHealth Hospice",
    type: "Non-profit",
    city: "Columbus",
    state: "OH",
    address: "800 McConnell Dr, Columbus, OH 43214",
    phone: "(614) 566-5377",
    website: "https://www.ohiohealth.com/services/hospice",
    rating: 4.7,
    services: ["Home Hospice", "Kobacker House (Inpatient)"],
    languages: ["English", "Somali"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '25',
    name: "Hospice of the Western Reserve",
    type: "Non-profit",
    city: "Cleveland",
    state: "OH",
    address: "17876 St Clair Ave, Cleveland, OH 44110",
    phone: "(800) 707-8922",
    website: "https://www.hospicewr.org",
    rating: 4.9,
    services: ["Home Hospice", "Inpatient Units", "Pediatric", "Music Therapy"],
    languages: ["English", "Spanish", "Arabic"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '26',
    name: "Hospice of Michigan",
    type: "Non-profit",
    city: "Detroit",
    state: "MI",
    address: "400 Mack Ave, Detroit, MI 48201",
    phone: "(888) 247-5701",
    website: "https://www.hom.org",
    rating: 4.6,
    services: ["Home Hospice", "Open Access", "Pediatric Anchors"],
    languages: ["English", "Arabic"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '27',
    name: "Our Lady of Peace",
    type: "Non-profit",
    city: "Minneapolis",
    state: "MN",
    address: "2076 St Anthony Ave, St Paul, MN 55104",
    phone: "(651) 789-5031",
    website: "https://ourladyofpeacemn.org",
    rating: 4.8,
    services: ["Home Hospice", "Residential Hospice", "End of Life Doula"],
    languages: ["English", "Hmong", "Somali"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  },
  {
    id: '28',
    name: "The Denver Hospice",
    type: "Non-profit",
    city: "Denver",
    state: "CO",
    address: "501 S Cherry St, Denver, CO 80246",
    phone: "(303) 321-2828",
    website: "https://thedenverhospice.org",
    rating: 4.7,
    services: ["Home Hospice", "Inpatient Care Center", "Footprints (Pediatric)"],
    languages: ["English", "Spanish"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '29',
    name: "BJC Hospice",
    type: "Non-profit",
    city: "St. Louis",
    state: "MO",
    address: "1935 Belt Way Dr, St. Louis, MO 63114",
    phone: "(314) 872-5050",
    website: "https://www.bjchospice.org",
    rating: 4.6,
    services: ["Home Hospice", "Evelyn's House (Inpatient)", "Music Therapy"],
    languages: ["English"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: true
  },
  {
    id: '30',
    name: "Nathan Adelson Hospice",
    type: "Non-profit",
    city: "Las Vegas",
    state: "NV",
    address: "4141 Swenson St, Las Vegas, NV 89119",
    phone: "(702) 733-0320",
    website: "https://www.nah.org",
    rating: 4.8,
    services: ["Home Hospice", "Inpatient Units", "Complementary Therapies"],
    languages: ["English", "Spanish", "Tagalog"],
    medicareCertified: true,
    acceptsMedicaid: true,
    nursing247: true,
    pediatric: false
  }
];

export const FAQS: FaqItem[] = [
  { question: "How do I know if it’s time for hospice?", answer: "Hospice is typically recommended when a doctor certifies that a patient has a life expectancy of 6 months or less if the illness runs its normal course, and the patient decides to focus on comfort care rather than curative treatment." },
  { question: "Does insurance cover hospice?", answer: "Yes, Medicare, Medicaid, and most private insurance plans cover hospice care in full, including medications, equipment, and visits related to the terminal diagnosis." },
  { question: "Can I change hospice agencies?", answer: "Yes, you have the right to switch hospice providers once per benefit period if you are unhappy with the care provided." },
  { question: "Can hospice be provided in a nursing home?", answer: "Yes, hospice services can be delivered wherever the patient calls home, including nursing homes, assisted living facilities, and private residences." },
  { question: "What if my family disagrees?", answer: "This is common. It helps to have a family meeting with a social worker or palliative care specialist to clarify goals of care and ensure everyone understands the patient's prognosis and wishes." }
];

export const GLOSSARY: GlossaryTerm[] = [
  { term: "Palliative Care", definition: "Specialized medical care for people living with a serious illness. This type of care is focused on providing relief from the symptoms and stress of the illness. The goal is to improve quality of life for both the patient and the family." },
  { term: "Hospice Care", definition: "A type of health care that focuses on the palliation of a terminally ill patient's pain and symptoms and attending to their emotional and spiritual needs at the end of life." },
  { term: "DNR (Do Not Resuscitate)", definition: "A medical order written by a doctor. It instructs health care providers not to do cardiopulmonary resuscitation (CPR) if a patient's breathing stops or if the patient's heart stops beating." },
  { term: "Advance Directive", definition: "Legal documents that allow you to spell out your decisions about end-of-life care ahead of time." },
  { term: "Health Care Proxy", definition: "A document that appoints someone you trust to make medical decisions for you if you cannot make them yourself." }
];

export const US_STATES = [
  "AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA",
  "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD",
  "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ",
  "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC",
  "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
];